name: Testing stuff

on:
  push:
    branches:
      - main

env:
  SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: join
        env:
          JOINED_MESSAGES: ${{ join(github.event.commits.*.message) }}
        run: echo "$JOINED_MESSAGES"
      - name: contains
        env:
          CONTAINS_SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}
        run: echo "$CONTAINS_SKIP"
      - name: if not skip
        run: echo "Not skipped, value of SKIP is $SKIP"

